export const routeWhiteList = [
  'Dashboard',
  'FleetOverview',
  'CargoTracking',
  'OrderList',
  'OrderDetail',
  'DeviceStatus',
  'RiskCenter',
  'DriverRating',
  'AddressChangeReview',
  'UnloadAddressConfirm',
  'PersonnelManagement',
  'DriverTasks',
  'SmartAssistant',
  'WarehouseManagement',
  'AlertCenter',
  'NavigationPortal',
  'overview',
  'tracking',
  'dispatch',
  'driver',
  'alerts',
  'warehouse',
  'assistant',
  'portal',
  '_BACK',
  '_REFRESH',
]

export const routeNameMap: Record<string, string> = {
  Dashboard: 'overview',
  FleetOverview: 'dispatch',
  CargoTracking: 'tracking',
  OrderList: 'tracking',
  OrderDetail: 'tracking',
  DeviceStatus: 'warehouse',
  RiskCenter: 'alerts',
  DriverRating: 'tracking',
  AddressChangeReview: 'tracking',
  UnloadAddressConfirm: 'tracking',
  PersonnelManagement: 'personnel',
  DriverTasks: 'driver',
  SmartAssistant: 'assistant',
  WarehouseManagement: 'warehouse',
  AlertCenter: 'alerts',
  NavigationPortal: 'portal',
}
